// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwtufcjziuqjqvoaishi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3dHVmY2p6aXVxanF2b2Fpc2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTk1NzUsImV4cCI6MjA3MjY3NTU3NX0.Q71NokAVK7R4IWqYhC9hw6CWcRLYo_gwV6PkSCKd1O0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});